// pnpm licenses list --prod --json 결과와 각 패키지의 LICENSE 파일(없으면 소스 헤더 또는 공식 저장소)에서
// 추출한 저작권 고지입니다. 의존성이 바뀌면 다시 생성해야 합니다.

export interface OpenSourceLicenseEntry {
  name: string
  version: string
  license: string
  homepage: string | null
  copyright: string | null
  note: string | null
}

export const OPEN_SOURCE_LICENSES: OpenSourceLicenseEntry[] = [
  {
    name: '@assistant-ui/core',
    version: '0.3.19',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: '@assistant-ui/react',
    version: '0.15.20',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: '@assistant-ui/react-markdown',
    version: '0.14.15',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: '@assistant-ui/store',
    version: '0.3.13',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: '@assistant-ui/tap',
    version: '0.9.17',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: '@babel/runtime',
    version: '7.29.7',
    license: 'MIT',
    homepage: 'https://babel.dev/docs/en/next/babel-runtime',
    copyright: 'Copyright (c) 2014-present Sebastian McKenzie and other contributors',
    note: null,
  },
  {
    name: '@base-ui/react',
    version: '1.8.0',
    license: 'MIT',
    homepage: 'https://base-ui.com',
    copyright: 'Copyright (c) 2019 Material-UI SAS',
    note: null,
  },
  {
    name: '@base-ui/utils',
    version: '0.4.0',
    license: 'MIT',
    homepage: 'https://github.com/mui/base-ui#readme',
    copyright: 'Copyright (c) 2019 Material-UI SAS',
    note: null,
  },
  {
    name: '@floating-ui/core',
    version: '1.8.0',
    license: 'MIT',
    homepage: 'https://floating-ui.com',
    copyright: 'Copyright (c) 2021-present Floating UI contributors',
    note: null,
  },
  {
    name: '@floating-ui/dom',
    version: '1.8.0',
    license: 'MIT',
    homepage: 'https://floating-ui.com',
    copyright: 'Copyright (c) 2021-present Floating UI contributors',
    note: null,
  },
  {
    name: '@floating-ui/react-dom',
    version: '2.1.9',
    license: 'MIT',
    homepage: 'https://floating-ui.com/docs/react-dom',
    copyright: 'Copyright (c) 2021-present Floating UI contributors',
    note: null,
  },
  {
    name: '@floating-ui/utils',
    version: '0.2.12',
    license: 'MIT',
    homepage: 'https://floating-ui.com',
    copyright: 'Copyright (c) 2021-present Floating UI contributors',
    note: null,
  },
  {
    name: '@mlc-ai/web-llm',
    version: '0.2.85',
    license: 'Apache-2.0',
    homepage: 'https://github.com/mlc-ai/web-llm',
    copyright: null,
    note: 'LICENSE 파일에 저작권자가 채워져 있지 않습니다(Apache-2.0 템플릿 원문). GitHub 조직: mlc-ai',
  },
  {
    name: '@paddleocr/paddleocr-js',
    version: '0.4.2',
    license: 'Apache-2.0',
    homepage: 'https://github.com/PaddlePaddle/PaddleOCR/tree/main/paddleocr-js',
    copyright: null,
    note: 'LICENSE 파일이 배포되지 않았습니다. package.json 저자: PaddlePaddle Authors',
  },
  {
    name: '@protobufjs/aspromise',
    version: '1.1.2',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/base64',
    version: '1.1.2',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/codegen',
    version: '2.0.5',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/eventemitter',
    version: '1.1.1',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/fetch',
    version: '1.1.1',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/float',
    version: '1.0.2',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/path',
    version: '1.1.2',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/pool',
    version: '1.1.0',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/dcodeIO/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@protobufjs/utf8',
    version: '1.1.2',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/protobufjs/protobuf.js#readme',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: '@radix-ui/number',
    version: '1.1.3',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/primitive',
    version: '1.1.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-accessible-icon',
    version: '1.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-accordion',
    version: '1.2.20',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-alert-dialog',
    version: '1.1.23',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-arrow',
    version: '1.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-aspect-ratio',
    version: '1.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-avatar',
    version: '1.2.6',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-checkbox',
    version: '1.3.11',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-collapsible',
    version: '1.1.20',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-collection',
    version: '1.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-compose-refs',
    version: '1.1.5',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-context',
    version: '1.2.2',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-context-menu',
    version: '2.3.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-dialog',
    version: '1.1.23',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-direction',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-dismissable-layer',
    version: '1.1.19',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-dropdown-menu',
    version: '2.1.24',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-focus-guards',
    version: '1.1.6',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-focus-scope',
    version: '1.1.16',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-form',
    version: '0.1.16',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-hover-card',
    version: '1.1.23',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-id',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-label',
    version: '2.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-menu',
    version: '2.1.24',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-menubar',
    version: '1.1.24',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-navigation-menu',
    version: '1.2.22',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-one-time-password-field',
    version: '0.1.16',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-password-toggle-field',
    version: '0.1.11',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-popover',
    version: '1.1.23',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-popper',
    version: '1.3.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-portal',
    version: '1.1.17',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-presence',
    version: '1.1.10',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-primitive',
    version: '2.1.10',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-progress',
    version: '1.1.16',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-radio-group',
    version: '1.4.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-roving-focus',
    version: '1.1.19',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-scroll-area',
    version: '1.2.18',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-select',
    version: '2.3.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-separator',
    version: '1.1.15',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-slider',
    version: '1.4.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-slot',
    version: '1.3.3',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-switch',
    version: '1.3.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-tabs',
    version: '1.1.21',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-toast',
    version: '1.2.23',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-toggle',
    version: '1.1.18',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-toggle-group',
    version: '1.1.19',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-toolbar',
    version: '1.1.19',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-tooltip',
    version: '1.2.16',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-callback-ref',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-controllable-state',
    version: '1.2.6',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-effect-event',
    version: '0.0.5',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-escape-keydown',
    version: '1.1.5',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-is-hydrated',
    version: '0.1.3',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-layout-effect',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-previous',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-rect',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-use-size',
    version: '1.1.4',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/react-visually-hidden',
    version: '1.2.11',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@radix-ui/rect',
    version: '1.1.3',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: '@sqlite.org/sqlite-wasm',
    version: '3.53.4-build1',
    license: 'Apache-2.0',
    homepage: 'https://github.com/sqlite/sqlite-wasm#readme',
    copyright: null,
    note: 'LICENSE 파일이 배포되지 않았습니다. package.json 저자: Thomas Steiner (tomac@google.com)',
  },
  {
    name: '@standard-schema/spec',
    version: '1.1.0',
    license: 'MIT',
    homepage: 'https://standardschema.dev',
    copyright: 'Copyright (c) 2024 Colin McDonnell',
    note: null,
  },
  {
    name: '@techstark/opencv-js',
    version: '4.10.0-release.1',
    license: 'Apache-2.0',
    homepage: 'https://github.com/TechStark/opencv-js#readme',
    copyright: null,
    note: 'LICENSE 파일에 저작권자가 채워져 있지 않습니다(Apache-2.0 템플릿 원문). GitHub: TechStark. 번들된 OpenCV.js 바이너리의 원저작권은 OpenCV 재단에 있습니다.',
  },
  {
    name: '@types/debug',
    version: '4.1.13',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/debug',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/estree',
    version: '1.0.9',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/estree',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/estree-jsx',
    version: '1.0.5',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/estree-jsx',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/hast',
    version: '3.0.5',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hast',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/mdast',
    version: '4.0.4',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mdast',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/ms',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ms',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/node',
    version: '24.13.5',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/react',
    version: '19.3.0',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@types/unist',
    version: '2.0.11, 3.0.3',
    license: 'MIT',
    homepage: 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/unist',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: '@ungap/structured-clone',
    version: '1.4.0',
    license: 'ISC',
    homepage: 'https://github.com/ungap/structured-clone#readme',
    copyright: 'Copyright (c) 2021, Andrea Giammarchi, @WebReflection',
    note: null,
  },
  {
    name: 'argparse',
    version: '2.0.1',
    license: 'Python-2.0',
    homepage: 'https://github.com/nodeca/argparse#readme',
    copyright: 'Copyright (c) 1991 - 1995, Stichting Mathematisch Centrum Amsterdam,',
    note: null,
  },
  {
    name: 'aria-hidden',
    version: '1.2.6',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/aria-hidden#readme',
    copyright: 'Copyright (c) 2017 Anton Korzunov',
    note: null,
  },
  {
    name: 'assistant-cloud',
    version: '0.2.1',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: 'assistant-stream',
    version: '0.3.43',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: 'bail',
    version: '2.0.2',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/bail#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'ccount',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/ccount#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'character-entities',
    version: '2.0.2',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/character-entities#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'character-entities-html4',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/character-entities-html4#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'character-entities-legacy',
    version: '3.0.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/character-entities-legacy#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'character-reference-invalid',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/character-reference-invalid#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'class-variance-authority',
    version: '0.7.1',
    license: 'Apache-2.0',
    homepage: 'https://github.com/joe-bell/cva#readme',
    copyright: 'Copyright 2022 Joe Bell',
    note: null,
  },
  {
    name: 'classnames',
    version: '2.5.1',
    license: 'MIT',
    homepage: 'https://github.com/JedWatson/classnames#readme',
    copyright: 'Copyright (c) 2018 Jed Watson',
    note: null,
  },
  {
    name: 'clipper-lib',
    version: '6.4.2',
    license: 'BSL',
    homepage: 'https://github.com/junmer/clipper-lib#readme',
    copyright: 'Copyright: Angus Johnson 2010-2017; Copyright (c) 2005 Tom Wu(번들된 BigInteger)',
    note: '소스 코드 헤더 기준(LICENSE 파일 미배포)',
  },
  {
    name: 'clsx',
    version: '2.1.1',
    license: 'MIT',
    homepage: 'https://github.com/lukeed/clsx#readme',
    copyright: 'Copyright (c) Luke Edwards <luke.edwards05@gmail.com> (lukeed.com)',
    note: null,
  },
  {
    name: 'cn',
    version: '0.2.6',
    license: 'MIT',
    homepage: 'https://github.com/shadcn-ui/cn#readme',
    copyright: 'Copyright (c) 2026 shadcn',
    note: null,
  },
  {
    name: 'comma-separated-tokens',
    version: '2.0.3',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/comma-separated-tokens#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'cookie-es',
    version: '3.1.1',
    license: 'MIT',
    homepage: 'https://github.com/unjs/cookie-es#readme',
    copyright:
      'Copyright (c) 2012-2014 Roman Shtylman <shtylman@gmail.com>; Copyright (c) 2015 Douglas Christopher Wilson <doug@somethingdoug.com>; Copyright (c) 2015 Nathan Friedly <nathan@nfriedly.com> (http://nfriedly.com/)',
    note: null,
  },
  {
    name: 'csstype',
    version: '3.2.3',
    license: 'MIT',
    homepage: 'https://github.com/frenic/csstype#readme',
    copyright: 'Copyright (c) 2017-2018 Fredrik Nicol',
    note: null,
  },
  {
    name: 'debug',
    version: '4.4.3',
    license: 'MIT',
    homepage: 'https://github.com/debug-js/debug#readme',
    copyright:
      'Copyright (c) 2014-2017 TJ Holowaychuk <tj@vision-media.ca>; Copyright (c) 2018-2021 Josh Junon',
    note: null,
  },
  {
    name: 'decode-named-character-reference',
    version: '1.3.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/decode-named-character-reference#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'dequal',
    version: '2.0.3',
    license: 'MIT',
    homepage: 'https://github.com/lukeed/dequal#readme',
    copyright: 'Copyright (c) Luke Edwards <luke.edwards05@gmail.com> (lukeed.com)',
    note: null,
  },
  {
    name: 'detect-node-es',
    version: '1.1.0',
    license: 'MIT',
    homepage: 'https://github.com/thekashey/detect-node',
    copyright: 'Copyright (c) 2017 Ilya Kantor',
    note: null,
  },
  {
    name: 'devlop',
    version: '1.1.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/devlop#readme',
    copyright: 'Copyright (c) 2023 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'escape-string-regexp',
    version: '5.0.0',
    license: 'MIT',
    homepage: 'https://github.com/sindresorhus/escape-string-regexp#readme',
    copyright: 'Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (https://sindresorhus.com)',
    note: null,
  },
  {
    name: 'estree-util-is-identifier-name',
    version: '3.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/estree-util-is-identifier-name#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'extend',
    version: '3.0.2',
    license: 'MIT',
    homepage: 'https://github.com/justmoon/node-extend#readme',
    copyright: 'Copyright (c) 2014 Stefan Thomas',
    note: null,
  },
  {
    name: 'flatbuffers',
    version: '25.9.23',
    license: 'Apache-2.0',
    homepage: 'https://google.github.io/flatbuffers/',
    copyright: 'Copyright 2014 Google Inc.',
    note: '소스 코드 헤더 기준(LICENSE 파일은 템플릿 원문)',
  },
  {
    name: 'get-nonce',
    version: '1.0.1',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/get-nonce',
    copyright: 'Copyright (c) 2020 Anton Korzunov',
    note: null,
  },
  {
    name: 'guid-typescript',
    version: '1.0.9',
    license: 'ISC',
    homepage: 'https://github.com/NicolasDeveloper/guid-typescript#readme',
    copyright: null,
    note: 'LICENSE 파일이 배포되지 않았습니다. package.json 저자: nicolas',
  },
  {
    name: 'hast-util-to-jsx-runtime',
    version: '2.3.6',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/hast-util-to-jsx-runtime#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'hast-util-whitespace',
    version: '3.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/hast-util-whitespace#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'html-url-attributes',
    version: '3.0.1',
    license: 'MIT',
    homepage: 'https://github.com/rehypejs/rehype-minify/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer',
    note: null,
  },
  {
    name: 'inline-style-parser',
    version: '0.2.7',
    license: 'MIT',
    homepage: 'https://github.com/remarkablemark/inline-style-parser#readme',
    copyright: 'Copyright (c) 2012 TJ Holowaychuk <tj@vision-media.ca>',
    note: null,
  },
  {
    name: 'is-alphabetical',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/is-alphabetical#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'is-alphanumerical',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/is-alphanumerical#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'is-decimal',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/is-decimal#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'is-hexadecimal',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/is-hexadecimal#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'is-plain-obj',
    version: '4.1.0',
    license: 'MIT',
    homepage: 'https://github.com/sindresorhus/is-plain-obj#readme',
    copyright: 'Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (https://sindresorhus.com)',
    note: null,
  },
  {
    name: 'js-yaml',
    version: '4.3.2',
    license: 'MIT',
    homepage: 'https://github.com/nodeca/js-yaml#readme',
    copyright: 'Copyright (C) 2011-2015 by Vitaly Puzrin',
    note: null,
  },
  {
    name: 'kiwi-nlp',
    version: '0.24.0',
    license: 'Apache-2.0',
    homepage: 'https://lab.bab2min.pe.kr/kiwi',
    copyright: 'Copyright 2017-2026 Minchul Lee and the Kiwi contributors',
    note: '저장소 NOTICE 파일 기준 (LICENSE 파일 자체에는 저작권자 표시 없음)',
  },
  {
    name: 'loglevel',
    version: '1.9.2',
    license: 'MIT',
    homepage: 'https://github.com/pimterry/loglevel',
    copyright: 'Copyright (c) 2013 Tim Perry',
    note: '저장소 LICENSE-MIT 기준(배포 패키지에는 LICENSE 파일 미포함)',
  },
  {
    name: 'long',
    version: '5.3.2',
    license: 'Apache-2.0',
    homepage: 'https://github.com/dcodeIO/long.js#readme',
    copyright:
      'Copyright 2009 The Closure Library Authors; Copyright 2020 Daniel Wirtz / The long.js Authors.',
    note: '소스 코드 헤더 기준(LICENSE 파일은 템플릿 원문)',
  },
  {
    name: 'longest-streak',
    version: '3.1.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/longest-streak#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <mailto:tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'lucide-react',
    version: '1.46.0',
    license: 'ISC',
    homepage: 'https://lucide.dev',
    copyright:
      'Copyright (c) 2026 Lucide Icons and Contributors; Copyright (c) 2013-present Cole Bemis',
    note: null,
  },
  {
    name: 'markdown-table',
    version: '3.0.4',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/markdown-table#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-find-and-replace',
    version: '3.0.2',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-find-and-replace#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-from-markdown',
    version: '2.0.3',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-from-markdown#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm',
    version: '3.1.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm-autolink-literal',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm-autolink-literal#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm-footnote',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm-footnote#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm-strikethrough',
    version: '2.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm-strikethrough#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm-table',
    version: '2.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm-table#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-gfm-task-list-item',
    version: '2.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-gfm-task-list-item#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-mdx-expression',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-mdx-expression#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-mdx-jsx',
    version: '3.2.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-mdx-jsx#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-mdxjs-esm',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-mdxjs-esm#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-phrasing',
    version: '4.1.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-phrasing#readme',
    copyright:
      'Copyright (c) 2017 Titus Wormer <tituswormer@gmail.com>; Copyright (c) 2017 Victor Felder <victor@draft.li>',
    note: null,
  },
  {
    name: 'mdast-util-to-hast',
    version: '13.2.1',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-to-hast#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-to-markdown',
    version: '2.1.2',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-to-markdown#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'mdast-util-to-string',
    version: '4.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/mdast-util-to-string#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark',
    version: '4.0.2',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-core-commonmark',
    version: '2.0.3',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm',
    version: '3.0.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-autolink-literal',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-autolink-literal#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-footnote',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-footnote#readme',
    copyright: 'Copyright (c) 2021 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-strikethrough',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-strikethrough#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-table',
    version: '2.1.2',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-table#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-tagfilter',
    version: '2.0.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-tagfilter#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-extension-gfm-task-list-item',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark-extension-gfm-task-list-item#readme',
    copyright: 'Copyright (c) 2020 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-factory-destination',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-factory-label',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-factory-space',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-factory-title',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-factory-whitespace',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-character',
    version: '2.1.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-chunked',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-classify-character',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-combine-extensions',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-decode-numeric-character-reference',
    version: '2.0.2',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-decode-string',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-encode',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-html-tag-name',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-normalize-identifier',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-resolve-all',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-sanitize-uri',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-subtokenize',
    version: '2.1.0',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-symbol',
    version: '2.0.1',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'micromark-util-types',
    version: '2.0.2',
    license: 'MIT',
    homepage: 'https://github.com/micromark/micromark/tree/main#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'ms',
    version: '2.1.3',
    license: 'MIT',
    homepage: 'https://github.com/vercel/ms#readme',
    copyright: 'Copyright (c) 2020 Vercel, Inc.',
    note: null,
  },
  {
    name: 'nanoid',
    version: '6.0.1',
    license: 'MIT',
    homepage: 'https://github.com/ai/nanoid#readme',
    copyright: 'Copyright 2017 Andrey Sitnik <andrey@sitnik.es>',
    note: null,
  },
  {
    name: 'onnxruntime-common',
    version: '1.30.0',
    license: 'MIT',
    homepage: 'https://github.com/Microsoft/onnxruntime#readme',
    copyright: 'Copyright (c) Microsoft Corporation',
    note: '저장소 LICENSE 기준(배포 패키지에는 LICENSE 파일 미포함)',
  },
  {
    name: 'onnxruntime-web',
    version: '1.30.0',
    license: 'MIT',
    homepage: 'https://github.com/Microsoft/onnxruntime#readme',
    copyright: 'Copyright (c) Microsoft Corporation',
    note: '저장소 LICENSE 기준(배포 패키지에는 LICENSE 파일 미포함)',
  },
  {
    name: 'parse-entities',
    version: '4.0.2',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/parse-entities#readme',
    copyright: 'Copyright (c) Titus Wormer <mailto:tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'pdfjs-dist',
    version: '6.3.289',
    license: 'Apache-2.0',
    homepage: 'https://mozilla.github.io/pdf.js/',
    copyright: 'Copyright 2012 Mozilla Foundation',
    note: '소스 코드 헤더 기준(LICENSE 파일에 저작권자 표시 없음)',
  },
  {
    name: 'platform',
    version: '1.3.6',
    license: 'MIT',
    homepage: 'https://github.com/bestiejs/platform.js#readme',
    copyright: 'Copyright 2014-2020 Benjamin Tan; Copyright 2011-2013 John-David Dalton',
    note: null,
  },
  {
    name: 'property-information',
    version: '7.2.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/property-information#readme',
    copyright: 'Copyright (c) Titus Wormer <mailto:tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'protobufjs',
    version: '7.6.6',
    license: 'BSD-3-Clause',
    homepage: 'https://protobufjs.github.io/protobuf.js/',
    copyright: 'Copyright (c) 2016, Daniel Wirtz  All rights reserved.',
    note: null,
  },
  {
    name: 'radix-ui',
    version: '1.6.7',
    license: 'MIT',
    homepage: 'https://radix-ui.com/primitives',
    copyright: 'Copyright (c) 2022 WorkOS',
    note: null,
  },
  {
    name: 'react',
    version: '19.3.0',
    license: 'MIT',
    homepage: 'https://react.dev/',
    copyright: 'Copyright (c) Meta Platforms, Inc. and affiliates.',
    note: null,
  },
  {
    name: 'react-dom',
    version: '19.3.0',
    license: 'MIT',
    homepage: 'https://react.dev/',
    copyright: 'Copyright (c) Meta Platforms, Inc. and affiliates.',
    note: null,
  },
  {
    name: 'react-markdown',
    version: '10.1.0',
    license: 'MIT',
    homepage: 'https://github.com/remarkjs/react-markdown#readme',
    copyright: 'Copyright (c) Espen Hovlandsdal',
    note: null,
  },
  {
    name: 'react-remove-scroll',
    version: '2.7.2',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/react-remove-scroll#readme',
    copyright: 'Copyright (c) 2017 Anton Korzunov',
    note: null,
  },
  {
    name: 'react-remove-scroll-bar',
    version: '2.3.8',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/react-remove-scroll-bar#readme',
    copyright: 'Copyright (c) 2025 Anton Korzunov <thekashey@gmail.com>',
    note: '저장소 LICENSE 기준(배포 패키지에는 LICENSE 파일 미포함)',
  },
  {
    name: 'react-resizable-panels',
    version: '4.12.4',
    license: 'MIT',
    homepage: 'https://react-resizable-panels.vercel.app/',
    copyright: 'Copyright (c) 2018 Brian Vaughn',
    note: null,
  },
  {
    name: 'react-router',
    version: '8.3.1',
    license: 'MIT',
    homepage: 'https://github.com/remix-run/react-router#readme',
    copyright:
      'Copyright (c) React Training LLC 2015-2019; Copyright (c) Remix Software Inc. 2020-2021; Copyright (c) Shopify Inc. 2022-2023',
    note: null,
  },
  {
    name: 'react-style-singleton',
    version: '2.2.3',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/react-style-singleton#readme',
    copyright: 'Copyright (c) 2017 Anton Korzunov',
    note: null,
  },
  {
    name: 'react-textarea-autosize',
    version: '8.5.9',
    license: 'MIT',
    homepage: 'https://github.com/Andarist/react-textarea-autosize#readme',
    copyright: 'Copyright (c) 2013 Andrey Popp',
    note: null,
  },
  {
    name: 'remark-gfm',
    version: '4.0.1',
    license: 'MIT',
    homepage: 'https://github.com/remarkjs/remark-gfm#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'remark-parse',
    version: '11.0.0',
    license: 'MIT',
    homepage: 'https://remark.js.org',
    copyright: 'Copyright (c) 2014 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'remark-rehype',
    version: '11.1.2',
    license: 'MIT',
    homepage: 'https://github.com/remarkjs/remark-rehype#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'remark-stringify',
    version: '11.0.0',
    license: 'MIT',
    homepage: 'https://remark.js.org',
    copyright: 'Copyright (c) 2014 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'reselect',
    version: '5.3.0',
    license: 'MIT',
    homepage: 'https://github.com/reduxjs/reselect#readme',
    copyright: 'Copyright (c) 2015-2018 Reselect Contributors',
    note: null,
  },
  {
    name: 'safe-content-frame',
    version: '0.0.30',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/safe-content-frame',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: 'scheduler',
    version: '0.28.0',
    license: 'MIT',
    homepage: 'https://react.dev/',
    copyright: 'Copyright (c) Meta Platforms, Inc. and affiliates.',
    note: null,
  },
  {
    name: 'secure-json-parse',
    version: '4.1.0',
    license: 'BSD-3-Clause',
    homepage: 'https://github.com/fastify/secure-json-parse#readme',
    copyright:
      'Copyright (c) 2019, Sideway Inc, and project contributors; Copyright (c) 2019-present The Fastify team',
    note: null,
  },
  {
    name: 'space-separated-tokens',
    version: '2.0.2',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/space-separated-tokens#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'stringify-entities',
    version: '4.0.4',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/stringify-entities#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <mailto:tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'style-to-js',
    version: '1.1.21',
    license: 'MIT',
    homepage: 'https://github.com/remarkablemark/style-to-js#readme',
    copyright: 'Copyright (c) 2020 Menglin "Mark" Xu <mark@remarkablemark.org>',
    note: null,
  },
  {
    name: 'style-to-object',
    version: '1.0.14',
    license: 'MIT',
    homepage: 'https://github.com/remarkablemark/style-to-object#readme',
    copyright: 'Copyright (c) 2017 Menglin "Mark" Xu <mark@remarkablemark.org>',
    note: null,
  },
  {
    name: 'tailwindcss',
    version: '4.3.3',
    license: 'MIT',
    homepage: 'https://tailwindcss.com',
    copyright: 'Copyright (c) Tailwind Labs, Inc.',
    note: null,
  },
  {
    name: 'trim-lines',
    version: '3.0.1',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/trim-lines#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <mailto:tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'trough',
    version: '2.2.0',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/trough#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'tslib',
    version: '2.8.1',
    license: '0BSD',
    homepage: 'https://www.typescriptlang.org/',
    copyright: 'Copyright (c) Microsoft Corporation.',
    note: null,
  },
  {
    name: 'tw-animate-css',
    version: '1.4.0',
    license: 'MIT',
    homepage: 'https://github.com/Wombosvideo/tw-animate-css#readme',
    copyright: 'Copyright (c) 2025 Wombosvideo',
    note: null,
  },
  {
    name: 'tw-shimmer',
    version: '0.4.13',
    license: 'MIT',
    homepage: 'https://www.assistant-ui.com/tw-shimmer',
    copyright: 'Copyright (c) 2025 AgentbaseAI Inc.',
    note: null,
  },
  {
    name: 'undici-types',
    version: '7.18.2',
    license: 'MIT',
    homepage: 'https://undici.nodejs.org',
    copyright: 'Copyright (c) Matteo Collina and Undici contributors',
    note: null,
  },
  {
    name: 'unified',
    version: '11.0.5',
    license: 'MIT',
    homepage: 'https://unifiedjs.com',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'unist-util-is',
    version: '6.0.1',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/unist-util-is#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'unist-util-position',
    version: '5.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/unist-util-position#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'unist-util-stringify-position',
    version: '4.0.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/unist-util-stringify-position#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'unist-util-visit',
    version: '5.1.0',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/unist-util-visit#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'unist-util-visit-parents',
    version: '6.0.2',
    license: 'MIT',
    homepage: 'https://github.com/syntax-tree/unist-util-visit-parents#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'use-callback-ref',
    version: '1.3.3',
    license: 'MIT',
    homepage: null,
    copyright: 'Copyright (c) 2017 Anton Korzunov',
    note: null,
  },
  {
    name: 'use-composed-ref',
    version: '1.4.0',
    license: 'MIT',
    homepage: 'https://github.com/Andarist/use-composed-ref#readme',
    copyright: null,
    note: 'LICENSE 파일 및 저작권 고지를 찾지 못했습니다.',
  },
  {
    name: 'use-isomorphic-layout-effect',
    version: '1.2.1',
    license: 'MIT',
    homepage: 'https://github.com/Andarist/use-isomorphic-layout-effect#readme',
    copyright: 'Copyright (c) Mateusz Burzyński',
    note: null,
  },
  {
    name: 'use-latest',
    version: '1.3.0',
    license: 'MIT',
    homepage: 'https://github.com/Andarist/use-latest#readme',
    copyright: 'Copyright (c) Andarist',
    note: null,
  },
  {
    name: 'use-sidecar',
    version: '1.1.3',
    license: 'MIT',
    homepage: 'https://github.com/theKashey/use-sidecar',
    copyright: 'Copyright (c) 2017 Anton Korzunov',
    note: null,
  },
  {
    name: 'use-sync-external-store',
    version: '1.7.0',
    license: 'MIT',
    homepage: 'https://github.com/react/react#readme',
    copyright: 'Copyright (c) Meta Platforms, Inc. and affiliates.',
    note: null,
  },
  {
    name: 'vfile',
    version: '6.0.3',
    license: 'MIT',
    homepage: 'https://github.com/vfile/vfile#readme',
    copyright: 'Copyright (c) 2015 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'vfile-message',
    version: '4.0.3',
    license: 'MIT',
    homepage: 'https://github.com/vfile/vfile-message#readme',
    copyright: 'Copyright (c) Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
  {
    name: 'zod',
    version: '4.6.5',
    license: 'MIT',
    homepage: 'https://zod.dev',
    copyright: 'Copyright (c) 2025 Colin McDonnell',
    note: null,
  },
  {
    name: 'zustand',
    version: '5.0.15',
    license: 'MIT',
    homepage: 'https://github.com/pmndrs/zustand',
    copyright: 'Copyright (c) 2019 Paul Henschel',
    note: null,
  },
  {
    name: 'zwitch',
    version: '2.0.4',
    license: 'MIT',
    homepage: 'https://github.com/wooorm/zwitch#readme',
    copyright: 'Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>',
    note: null,
  },
]
